baseURL: https://www.abflex.kr
languageCode: ko-KR
title: 에이비플렉스
theme: "PaperMod"

params:
  homeInfoParams:
    Title: 에이비플렉스는 FPCB 전문 기업입니다
    Content: 스마트폰부터 전장 그리고 디스플레이 까지 다양한 영역의 FPCB를 개발하고 있습니다.
    
    
              특히 최근 폴더블 스마트폰, 롤러블 TV 등 FPCB를 활용한 디스플레이 사업이 크게 확장하고 있습니다.


              당사는 이러한 시류에 맞춰 다양한 FPCB 디스플레이 선행개발로 새로운 도약을 기대하고 있습니다. 
  socialIcons:
    - name: facebook
      url: "https://facebook.com/"
    - name: twitter
      url: "https://twitter.com/"
  cover:
    linkFullImages: ture
  ShowBreadCrumbs: ture
  ShowReadingTime: ture
  ShowShareButtons: ture
  ShowPostNavLinks: ture
  
menu:
  main:
    - identifier: categories
      name: 카테고리
      url: /categories/
      weight: 10
    - identifier: tags
      name: 태그
      url: /tags/
      weight: 20
    - identifier: archives
      name: 아카이브
      url: /archives/
      weight: 30